### PR TITLE
Run tests with GitHub Action

### PR DESCRIPTION
**Pull request by cbrnr**
This should restore our tests, which previously ran on Azure Pipelines.

### CODE REVIEW

**Comment by cbrnr** [comment]
The action only runs in my fork for now (until this PR is merged), here are the current results: https://github.com/cbrnr/pyxdf/actions/runs/8847040105

Any idea how to fix the `git` warning? It's due to the checkout of the examples repo, which does not get cleaned up properly or something.

**Comment by cbrnr** [comment]
OK, fixed, I accidentally added the submodule.

https://github.com/cbrnr/pyxdf/actions/runs/8847104484

**Comment by cbrnr** [comment]
@cboulay feel free to merge if you're happy with the changes.

**Review by cboulay — APPROVED** [review]
LGTM

**Pull request merged**
