### PR TITLE
Rename examples to cli

### PR DESCRIPTION
**Pull request by cbrnr**
I think `pyxdf.examples` should be named `pyxdf.cli`, as this is what it really contains.

In addition, I've enforced a line length of 88 (default of Black/Ruff).

### CODE REVIEW

**Review by cboulay — APPROVED** [review]
Looks good, thanks!

**Comment by sappelhoff** [comment]
IMHO https://github.com/xdf-modules/xdf-tagger could also live here, rather than in its own repo. It is very similar in scope to the other "examples".

**Comment by cbrnr** [comment]
@sappelhoff yes, I think so too! Would you be willing to submit a separate PR? I'd like to merge this one before adding new things.

**Comment by sappelhoff** [comment]
> Would you be willing to submit a separate PR? I'd like to merge this one before adding new things.

sure, I could do that. However, I think this should go hand in hand with updating the README and then archiving said repo, to avoid duplicates

**Pull request merged**
