### PR TITLE
Expose information about segments in info and "print_metadata"

### PR DESCRIPTION
**Pull request by agricolab**
Addresses #116

### CODE REVIEW

**Comment by cbrnr** [comment]
LGTM! Would it make sense to adapt the effective sampling frequency though? Currently, segments are ignored, which can lead to deviations if there are long(ish) gaps in the data. It would probably make more sense to compute an effective sampling frequency per segment and then average across segments?

**Comment by agricolab** [comment]
If one dejitters, calculation of the effective srate as weighted average across segments is the default anyways.

**Comment by agricolab** [comment]
So if it's okay, passes tests and has no conflicts, I'd merge this afternoon. Any opposing argument?

**Comment by cbrnr** [comment]
Thanks @agricolab, I went ahead and merged!

**Comment by cbrnr** [comment]
(I pushed a quick changelog entry after merging.)

**Pull request merged**
